// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7PpG344L_rwtycpmibBFTl-p_eqDZKvs',
    appId: '1:326678539539:web:e9e5f7e45d40a936b1bee6',
    messagingSenderId: '326678539539',
    projectId: 'truxoo-25f15',
    authDomain: 'truxoo-25f15.firebaseapp.com',
    storageBucket: 'truxoo-25f15.firebasestorage.app',
    measurementId: 'G-8VLXZ1XDXP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCw41kB4NmmtF0w1etFNf1a6zlq9d1Ijrc',
    appId: '1:326678539539:android:adf13dbb730193deb1bee6',
    messagingSenderId: '326678539539',
    projectId: 'truxoo-25f15',
    storageBucket: 'truxoo-25f15.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAR50YOvej5Y-FBHCS9PSmzcNDdcTA80nQ',
    appId: '1:326678539539:ios:8a20ce42bc5fc20eb1bee6',
    messagingSenderId: '326678539539',
    projectId: 'truxoo-25f15',
    storageBucket: 'truxoo-25f15.firebasestorage.app',
    iosBundleId: 'com.truxoo.truxoo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAR50YOvej5Y-FBHCS9PSmzcNDdcTA80nQ',
    appId: '1:326678539539:ios:8a20ce42bc5fc20eb1bee6',
    messagingSenderId: '326678539539',
    projectId: 'truxoo-25f15',
    storageBucket: 'truxoo-25f15.firebasestorage.app',
    iosBundleId: 'com.truxoo.truxoo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD7PpG344L_rwtycpmibBFTl-p_eqDZKvs',
    appId: '1:326678539539:web:771a67329610c245b1bee6',
    messagingSenderId: '326678539539',
    projectId: 'truxoo-25f15',
    authDomain: 'truxoo-25f15.firebaseapp.com',
    storageBucket: 'truxoo-25f15.firebasestorage.app',
    measurementId: 'G-HEKV74NYQG',
  );
}
